site_name: Documentacion de Arduino
theme:
  name: material
  language: es
  palette:
    - scheme: slate
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - index.md
  - Fundamentos:
    - Electronica:
      - Corriente DC y AC.md
      - Se√±ales.md
    - Lenguaje:
      - Variables.md
      - Funciones.md
      - Bucles de Control.md
      - Programacion OOP.md
    - Arduino:
      - Esquema Fisico.md
      - Funciones Basicas.md
  - Perifericos:
    - Digital:
      - Digital/Definicion.md
    - Analogicos:
      - Analog/Definicion.md
    - PWM:
      - PWM/Definicion.md
    - Serial:
      - Serial/Definicion.md
    - I2C:
      - I2C/Definicion.md
    - SPI:
      - SPI/Definicion.md


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js